# conda:
#     file: docs/environment.yml
# requirements_file: requirements.txt - this option seems to be ignored by RTD


formats:
    - htmlzip
python:
    setup_py_install: true
    pip_install: false
    version: 2.7
    extra_requirements:
      - docs
