FROM ubuntu:14.04
RUN apt-get update && apt-get install -y \
	build-essential \
	gcc-4.8 \
        g++-4.8 \
        cmake \
        libtclap-dev \
        libinsighttoolkit4.5 \
        libinsighttoolkit4-dev \
        libvtk5-dev \
        libvtk5-qt4-dev \
        libvtk5.8 \
        libvtk5.8-qt4 \
        tcl-vtk \
        libvtk-java \
        python-vtk \
        python-vtkgdcm \
        libncurses5  \
        libncurses5-dev \
  	libann-dev
